#page title
page_title                                : Inky - PDF Reader  # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
                                    # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Inky - PDF Reader & Editor & Converte     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Inky, the one-stop solution for all your PDF document needs. Read, edit, annotate with ink, organize with tags, merge, split, and convert files to PDF effortlessly. 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Andrea Del Bello                                
your_link                                 :                     
your_city                                 : Italy                               
email_address                             : inkypdf@gmail.com     
facebook_username                         :                                           
instagram_username                        : andreadelbello
github_username                           : andelby



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : PDF Reading Excellence
    description                           : Enjoy smooth and seamless PDF reading with Inky. Whether it's a textbook, research paper, or an important document, our app ensures crisp and clear rendering, making your reading experience enjoyable and distraction-free.
    fontawesome_icon_name                 : star
    
  - title                                 : Ink Annotation & Notes
    description                           : Unleash your creativity and productivity with ink annotation. Highlight important passages, underline key points, and add your thoughts directly to PDFs. Use notes for organized, accessible annotations that take your PDFs to the next level.
    fontawesome_icon_name                 : magic

  - title                                 : Organize with Tags
    description                           : Keep your documents in order with customizable tags. Quickly categorize and find your files, making it easy to stay organized, whether you're managing personal documents or work-related materials.
    fontawesome_icon_name                 : adjust

  - title                                 : Merge & Split PDFs
    description                           : Combine multiple PDFs into a single document with inky's merge feature. Need to divide a large PDF? No problem—splitting PDFs is just as simple.
    fontawesome_icon_name                 : link

  - title                                 : File Conversion Made Simple
    description                           : inky is not just a PDF tool—it's also a versatile file converter. Convert various file formats, such as Excel, PowerPoint (PPTX), Word documents, and images like JPEG, PNG, and TIFF, into high-quality PDFs. No more worrying about compatibility issues!
    fontawesome_icon_name                 : arrow-alt-circle-down
  
  - title                                 : Fluent Design Interface
    description                           : Inky seamlessly incorporates the Fluent Design System, Microsoft's flagship design language for Windows 11. Enjoy a visually captivating experience with elements like Acrylic material, soft animations, and consistent iconography that adhere to Windows 11's design philosophy, providing a harmonious and immersive interaction with your operating system.
    fontawesome_icon_name                 : info-circle

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
